# Input/output configuration
input_dir: ${EXATRKX_DATA}/run/feature_store
output_dir: ${EXATRKX_DATA}/run/gnn_evaluation
project: GNNStudy
edge_cut: 0.5

# Dataset parameters
pt_signal_min: 0.
pt_background_min: 0.
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[800, 100, 100]] # Number of [training, validation, testing] examples
noise: False
overwrite: True

# Model parameters
spatial_channels: 3
cell_channels: 0
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
aggregation: sum_max
hidden_activation: ReLU
weight: 2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime: [[pid]] #NOTE: [pid] assumes filtering has (not) been performed i.e. variable y_pid (y) exists in Data.
max_epochs: 50

# Post-processing
callbacks: [[GNNTelemetry, GNNBuilder]]
